In [1]:
import warnings 
warnings.filterwarnings('ignore')

In [2]:
pip install nltk


Note: you may need to restart the kernel to use updated packages.


In [3]:
import nltk

In [4]:
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('stopwords')
# named entity
nltk.download('maxent_ne_chunker')
nltk.download('averaged_perceptron_tagger')
nltk.download('words')


[nltk_data] Error loading punkt: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading wordnet: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading omw-1.4: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading stopwords: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>
[nltk_data] Error loading maxent_ne_chunker: <urlopen error [Errno
[nltk_data]     11001] getaddrinfo failed>
[nltk_data] Error loading averaged_perceptron_tagger: <urlopen error
[nltk_data]     [Errno 11001] getaddrinfo failed>
[nltk_data] Error loading words: <urlopen error [Errno 11001]
[nltk_data]     getaddrinfo failed>


False

In [5]:
import pandas as pd, numpy as np 
import matplotlib.pyplot as plt, seaborn as sns
import string

In [6]:
 import re # regular expression
 import nltk # natual language toolkit

In [7]:
from nltk.corpus import stopwords

In [8]:
 from nltk.tokenize import word_tokenize
 from nltk.stem import WordNetLemmatizer
 stop_words = stopwords.words()

In [9]:
data = pd.read_csv("IMDB Dataset.csv")
data.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [10]:
data.shape

(50000, 2)

In [11]:
data.rename(columns={'review':'text'},inplace=True)

In [12]:
def clening(text):
    text = text.lower() # converting to lowercase
    text = re.sub("\d", "", text) # removing number 
    text = re.sub('[<.*?>+]', '', text) # removing special characters, 
    text = re.sub('[%s]' % re.escape(string.punctuation), ' ', text) # punctuations
    text = re.sub('\n', '', text)
    text = re.sub('[’“”…]', '', text)
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  
                           u"\U0001F300-\U0001F5FF"  
                           u"\U0001F680-\U0001F6FF"  
                           u"\U0001F1E0-\U0001F1FF"  
                           u"\U00002702-\U000027B0"  
                           u"\U000024C2-\U0001F251"  
                           "]+", flags=re.UNICODE)
    text = emoji_pattern.sub(r'', text)
    text=re.sub("isn't",'is not',text)
    text=re.sub("he's",'he is',text)
    text=re.sub("wasn't",'was not',text)
    text=re.sub("there's",'there is',text)
    text=re.sub("couldn't",'could not',text)
    text=re.sub("won't",'will not',text)
    text=re.sub("they're",'they are',text)
    text=re.sub("she's",'she is',text)
    text=re.sub("There's",'there is',text)
    text=re.sub("wouldn't",'would not',text)
    text=re.sub("haven't",'have not',text)
    text=re.sub("That's",'That is',text)
    text=re.sub("you've",'you have',text)
    text=re.sub("He's",'He is',text)
    text=re.sub("what's",'what is',text)
    text=re.sub("weren't",'were not',text)
    text=re.sub("we're",'we are',text)
    text=re.sub("hasn't",'has not',text)
    text=re.sub("you'd",'you would',text)
    text=re.sub("shouldn't",'should not',text)
    text=re.sub("let's",'let us',text)
    text=re.sub("they've",'they have',text)
    text=re.sub("You'll",'You will',text)
    text=re.sub("i'm",'i am',text)
    text=re.sub("we've",'we have',text)
    text=re.sub("it's",'it is',text)
    text=re.sub("don't",'do not',text)
    text=re.sub("that´s",'that is',text)
    text=re.sub("I´m",'I am',text)
    text=re.sub("it’s",'it is',text)
    text=re.sub("she´s",'she is',text)
    text=re.sub("he’s'",'he is',text)
    text=re.sub('I’m','I am',text)
    text=re.sub('I’d','I did',text)
    text=re.sub("he’s'",'he is',text)
    text=re.sub('there’s','there is',text)
   
    return text

In [13]:
data['text']=data['text'].apply(clening)

In [14]:
data.head()

text sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production  the filming tec...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically there s a family where a little boy ...  negative
4  petter mattei s  love in the time of money  is...  positive

In [15]:
sw = stopwords.words('english')
print(sw)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [16]:
data['no_sw'] = data['text'].apply(lambda x: " ".join([word for word in x.split() if word not in (sw)]))
data.head()

text sentiment  \
0  one of the other reviewers has mentioned that ...  positive   
1  a wonderful little production  the filming tec...  positive   
2  i thought this was a wonderful way to spend ti...  positive   
3  basically there s a family where a little boy ...  negative   
4  petter mattei s  love in the time of money  is...  positive   

                                               no_sw  
0  one reviewers mentioned watching oz episode ho...  
1  wonderful little production filming technique ...  
2  thought wonderful way spend time hot summer we...  
3  basically family little boy jake thinks zombie...  
4  petter mattei love time money visually stunnin...

In [17]:
 wordnet_lm = WordNetLemmatizer()
 data['wordnet_lm'] = data['no_sw'].apply(wordnet_lm.lemmatize)
 data.head()

text sentiment  \
0  one of the other reviewers has mentioned that ...  positive   
1  a wonderful little production  the filming tec...  positive   
2  i thought this was a wonderful way to spend ti...  positive   
3  basically there s a family where a little boy ...  negative   
4  petter mattei s  love in the time of money  is...  positive   

                                               no_sw  \
0  one reviewers mentioned watching oz episode ho...   
1  wonderful little production filming technique ...   
2  thought wonderful way spend time hot summer we...   
3  basically family little boy jake thinks zombie...   
4  petter mattei love time money visually stunnin...   

                                          wordnet_lm  
0  one reviewers mentioned watching oz episode ho...  
1  wonderful little production filming technique ...  
2  thought wonderful way spend time hot summer we...  
3  basically family little boy jake thinks zombie...  
4  petter mattei love time money visually stunnin...

In [18]:
nb=data.drop(columns=['text','no_sw',])
nb.columns=['sentiment','review']
nb['sentiment']=nb['sentiment'].replace({'positive':1,'negative':0})
nb.head()

sentiment                                             review
0          1  one reviewers mentioned watching oz episode ho...
1          1  wonderful little production filming technique ...
2          1  thought wonderful way spend time hot summer we...
3          0  basically family little boy jake thinks zombie...
4          1  petter mattei love time money visually stunnin...

In [19]:
from sklearn.model_selection import train_test_split
X=nb['review']
y=nb['sentiment']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20,random_state=30)

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
vect=CountVectorizer()
X_train=vect.fit_transform(X_train)
X_test=vect.transform(X_test)

In [21]:
from sklearn.naive_bayes import ComplementNB #MultinomialNB,BernoulliNB
from sklearn.metrics import classification_report, confusion_matrix
CNB = ComplementNB()
CNB.fit(X_train, y_train)

ComplementNB()

In [22]:
from sklearn import metrics
predicted = CNB.predict(X_test)
accuracy_score = metrics.accuracy_score(predicted, y_test)
accuracy_score

0.8634

In [122]:
y_test.shape

(10000,)

In [23]:
print((confusion_matrix(y_test, predicted)))

[[4384  593]
 [ 773 4250]]


In [24]:
 print(classification_report(y_test, predicted))


              precision    recall  f1-score   support

           0       0.85      0.88      0.87      4977
           1       0.88      0.85      0.86      5023

    accuracy                           0.86     10000
   macro avg       0.86      0.86      0.86     10000
weighted avg       0.86      0.86      0.86     10000



# DATA 2

In [27]:
spam=pd.read_csv("spam (1).csv")
spam.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [28]:
spam.isnull().sum()

Category    0
Message     0
dtype: int64

In [124]:
def lening(Message):
    Message = Message.lower() # converting to lowercase
    Message = re.sub(r"\b\d+\b", "", Message) # removing number 
    Message = re.sub('<.*?>+', '', Message) # removing special characters, 
    Message = re.sub('[%s]' % re.escape(string.punctuation), ' ', Message) # punctuations
    Message = re.sub('\n', '', Message)
    Message = re.sub('[’“”…]', '', Message)
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  
                           u"\U0001F300-\U0001F5FF"  
                           u"\U0001F680-\U0001F6FF"  
                           u"\U0001F1E0-\U0001F1FF"  
                           u"\U00002702-\U000027B0"  
                           u"\U000024C2-\U0001F251"  
                           "]+", flags=re.UNICODE)
    Message = emoji_pattern.sub(r'', Message)
    Message=re.sub("isn't",'is not',Message)
    Message=re.sub("he's",'he is',Message)
    Message=re.sub("wasn't",'was not',Message)
    Message=re.sub("there's",'there is',Message)
    Message=re.sub("couldn't",'could not',Message)
    Message=re.sub("won't",'will not',Message)
    Message=re.sub("they're",'they are',Message)
    Message=re.sub("she's",'she is',Message)
    Message=re.sub("There's",'there is',Message)
    Message=re.sub("wouldn't",'would not',Message)
    Message=re.sub("haven't",'have not',Message)
    Message=re.sub("That's",'That is',Message)
    Message=re.sub("you've",'you have',Message)
    Message=re.sub("He's",'He is',Message)
    Message=re.sub("what's",'what is',Message)
    Message=re.sub("weren't",'were not',Message)
    Message=re.sub("we're",'we are',Message)
    Message=re.sub("hasn't",'has not',Message)
    Message=re.sub("you'd",'you would',Message)
    Message=re.sub("shouldn't",'should not',Message)
    Message=re.sub("let's",'let us',Message)
    Message=re.sub("they've",'they have',Message)
    Message=re.sub("You'll",'You will',Message)
    Message=re.sub("i'm",'i am',Message)
    Message=re.sub("we've",'we have',Message)
    Message=re.sub("it's",'it is',Message)
    Message=re.sub("don't",'do not',Message)
    Message=re.sub("that´s",'that is',Message)
    Message=re.sub("I´m",'I am',Message)
    Message=re.sub("it’s",'it is',Message)
    Message=re.sub("she´s",'she is',Message)
    Message=re.sub("he’s'",'he is',Message)
    Message=re.sub('I’m','I am',Message)
    Message=re.sub('I’d','I did',Message)
    Message=re.sub("he’s'",'he is',Message)
    Message=re.sub('there’s','there is',Message)
   
    return Message

In [30]:
spam['Message']=spam['Message'].apply(lening)

In [31]:
spam.head()

Category                                            Message
0      ham  go until jurong point  crazy   available only ...
1      ham                      ok lar    joking wif u oni   
2     spam  free entry in  a wkly comp to win fa cup final...
3      ham  u dun say so early hor    u c already then say   
4      ham  nah i don t think he goes to usf  he lives aro...

In [32]:
spam['Category']=spam['Category'].replace({'spam':1,'ham':0})

In [33]:
spam.head()

Category                                            Message
0         0  go until jurong point  crazy   available only ...
1         0                      ok lar    joking wif u oni   
2         1  free entry in  a wkly comp to win fa cup final...
3         0  u dun say so early hor    u c already then say   
4         0  nah i don t think he goes to usf  he lives aro...

In [34]:
sws= stopwords.words('english')
print(sws)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [35]:
spam['no_sws'] = spam['Message'].apply(lambda x: " ".join([word for word in x.split() if word not in (sws)]))
spam.head()

Category                                            Message  \
0         0  go until jurong point  crazy   available only ...   
1         0                      ok lar    joking wif u oni      
2         1  free entry in  a wkly comp to win fa cup final...   
3         0  u dun say so early hor    u c already then say      
4         0  nah i don t think he goes to usf  he lives aro...   

                                              no_sws  
0  go jurong point crazy available bugis n great ...  
1                            ok lar joking wif u oni  
2  free entry wkly comp win fa cup final tkts 21s...  
3                u dun say early hor u c already say  
4             nah think goes usf lives around though

In [36]:
wordnet_lm = WordNetLemmatizer()
spam['wordnet_lm'] = spam['no_sws'].apply(wordnet_lm.lemmatize)
spam.head()

Category                                            Message  \
0         0  go until jurong point  crazy   available only ...   
1         0                      ok lar    joking wif u oni      
2         1  free entry in  a wkly comp to win fa cup final...   
3         0  u dun say so early hor    u c already then say      
4         0  nah i don t think he goes to usf  he lives aro...   

                                              no_sws  \
0  go jurong point crazy available bugis n great ...   
1                            ok lar joking wif u oni   
2  free entry wkly comp win fa cup final tkts 21s...   
3                u dun say early hor u c already say   
4             nah think goes usf lives around though   

                                          wordnet_lm  
0  go jurong point crazy available bugis n great ...  
1                            ok lar joking wif u oni  
2  free entry wkly comp win fa cup final tkts 21s...  
3                u dun say early hor u c already say  
4             nah think goes usf lives around though

In [37]:
spam=spam.drop(columns=['Message','no_sws'])
spam.head()

Category                                         wordnet_lm
0         0  go jurong point crazy available bugis n great ...
1         0                            ok lar joking wif u oni
2         1  free entry wkly comp win fa cup final tkts 21s...
3         0                u dun say early hor u c already say
4         0             nah think goes usf lives around though

In [38]:
X_sent=spam['wordnet_lm']
y_sent=spam['Category']

In [39]:
from sklearn.model_selection import train_test_split
X_train_sent,X_test_sent,y_train_sent,y_test_sent=train_test_split(X_sent,y_sent,test_size=0.2,random_state=100)

In [40]:
X_train_sent

2747                                  k da many page want
4779    u r beautiful girl ive ever seen u r baby come...
338                                      sleeping surfing
507     maybe westshore hyde park village place near h...
3312    hi darlin work u get trouble ijust talked mum ...
                              ...                        
4149    please call amanda regard renewing upgrading c...
1890                             gotta collect da car lei
350      checking really miss seeing jeremiah great month
79                         still looking job much ta earn
3927                               havent add ü yet right
Name: wordnet_lm, Length: 4457, dtype: object

In [41]:
from sklearn.feature_extraction.text import CountVectorizer

In [42]:
vector=CountVectorizer()
X_train_sent=vector.fit_transform(X_train_sent)
X_test_sent=vector.transform(X_test_sent)

In [43]:
X_train_sent.toarray()[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [44]:
from sklearn.linear_model import LogisticRegression

In [45]:
log=LogisticRegression()

In [46]:
log.fit(X_train_sent,y_train_sent)

LogisticRegression()

In [47]:
log_pred_test=log.predict(X_test_sent)

In [48]:
log_pred_test[10]

1

In [49]:
X_train_sent[10]

<1x7090 sparse matrix of type '<class 'numpy.int64'>'
	with 19 stored elements in Compressed Sparse Row format>

In [50]:
par=['Hello  dear,hope to see you soon']

In [51]:
par_vect=vector.transform(par)

In [52]:
par_vect.toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [53]:
log.predict(par_vect)

array([0], dtype=int64)

In [54]:
from sklearn.metrics import classification_report,confusion_matrix

In [55]:
cm=confusion_matrix(y_test_sent,log_pred_test)

In [56]:
cm

array([[966,   2],
       [ 21, 126]], dtype=int64)

In [57]:
cr=classification_report(y_test_sent,log_pred_test)

In [58]:
print(cr)

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       968
           1       0.98      0.86      0.92       147

    accuracy                           0.98      1115
   macro avg       0.98      0.93      0.95      1115
weighted avg       0.98      0.98      0.98      1115

